services:
  api:
    image: sfbrief21
    labels:
      - traefik.enable=true
      - traefik.http.routers.apishop.rule=Host(`apishop.nocturlab.fr`)
      - traefik.http.services.apishop.loadbalancer.server.port=8080
    ports:
      - 8080:8080
    depends_on: 
      - db
    networks:
      - traefik
      - db
    environment:
      HOST: 0.0.0.0
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      POSTGRES_HOST: db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    networks:
      - db


networks:
 db:
 traefik:
  external: false
  name: traefik_default